planner:
  class_path: autogen_agentchat.agents.AssistantAgent
  llm_config:
    config_list_filter: { label: gemini }   # pulls key from .env
    temperature: 0.2
  human_input_mode: ALWAYS

runner:
  class_path: autogen_agentchat.agents.UserProxyAgent
  tools:
    - python     # runs wrappers from tasks.py
    - bash       # fallback for CLI scripts
  work_dir: "{workspace_root}"   # conductor formats this
  human_input_mode: NEVER

